### Publish message 
POST http://localhost:8000/publish 
Content-Type: application/json

{
    "orderId": "7"
}

### Save key/value pair 

POST http://localhost:8000/savekv 
Content-Type: application/json

{
    "orderId": "9006"
}

### Get key 

GET http://localhost:8000/getkv 
Content-Type: application/json

{
    "orderId": "90"
}

### Delete key

DELETE http://localhost:8000/deletekv 
Content-Type: application/json

{
    "orderId": "9006"
}