### Publish/Subscribe API 

POST http://localhost:5001/pubsub/orders
Content-Type: application/json

{
    "orderId": 1
}

### Request/Reply API 

POST http://localhost:5001/invoke/orders
Content-Type: application/json

{
    "orderId": 1
}

### Save KV 

POST http://localhost:5001/kv/orders
Content-Type: application/json

{
    "orderId": 13
}

### GET KV 

POST http://localhost:5001/pubsub/orders
Content-Type: application/json

{
    "orderId": "139025"
}