### Publish message 

POST http://localhost:9000/publish 
Content-Type: application/json

{
    "orderId": 12
}

###

POST https://http-prj101382.api.dev.cloud.diagrid.io/v1.0/publish/az-pub/orders
dapr-api-token: diagrid://v1/58e239cc-f716-48f2-bf5b-2a3a3154c51c/101382/quickstarts/newest/7de769ac-4f2d-425c-9683-48fe785db37f
Content-Type: application/json

{
    "orderId": "11787"
}

### Save key/value pair 

POST http://localhost:9000/savekv 
Content-Type: application/json

{
    "orderId": "9006"
}

### Get key 

GET http://localhost:9000/getkv 
Content-Type: application/json

{
    "orderId": "90"
}

### Delete key

DELETE http://localhost:9000/deletekv 
Content-Type: application/json

{
    "orderId": "9006"
}