apiVersion: cra.diagrid.io/v1beta1
kind: Connection
metadata:
  name: servicebus
spec:
  type: pubsub.azure.servicebus.topics
  version: v1
  metadata:
    - name: connectionString
      value: "{SB_CONNECTION_STRING}"
