### Key/Value API 

### Save KV 

POST http://localhost:5001/kv/orders
Content-Type: application/json

{
    "orderId": 1
}

### Get KV 

GET http://localhost:5001/kv/orders/1

### Delete KV 

DELETE http://localhost:5001/kv/orders/1