name = "checkout-http"
main = "src/worker.js"
compatibility_date = "2023-06-13"

[vars]
PUBSUB_NAME = "pubsub"
PUBSUB_TOPIC = "orders"
DAPR_HTTP_PORT = 443
DAPR_HOST = "<DAPR_HOST>"
CHECKOUT_API_TOKEN = "CHECKOUT_API_TOKEN"