name: CSharp Sample

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main
    paths:
      - ./github/workflows/csharp.yaml
      - csharp/*

jobs:
  build:
    runs-on: ubuntu-latest
    environment: shared-production
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-dotnet@v3
      with:
          dotnet-version: '6.0.x'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ vars.AWS_CI_ROLE }}
        aws-region: ${{ vars.AWS_CI_REGION }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: build local
      run: |
        cd csharp
        dotnet build

    - name: build and push container
      run: |
        cd csharp
        docker buildx build --platform linux/amd64 -t csharp-sample .
        docker tag csharp-sample:latest ${{ vars.AWS_PUBLIC_ECR_URL }}/csharp-sample:latest
        docker push ${{ vars.AWS_PUBLIC_ECR_URL }}/csharp-sample:latest

