name: Javascript Sample

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main
    paths:
    - .github/workflows/javascript.yaml
    - javascript/*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    environment: shared-production
    # Only run on main repo (not on forks)
    if: github.repository_owner == 'diagridio'
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: "**/package-lock.json"

    - name: build local
      run: |
        cd javascript
        npm install

    - name: build container
      run: |
        cd javascript
        docker buildx build --platform linux/amd64 -t javascript-sample .

    - name: Configure AWS credentials
      if: github.event_name != 'pull_request'
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ vars.AWS_CI_ROLE }}
        aws-region: ${{ vars.AWS_CI_REGION }}
    - name: Login to Amazon ECR
      if: github.event_name != 'pull_request'
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: public

    - name: push container
      if: github.event_name != 'pull_request'
      env:
        PUBLIC_ECR: "${{ steps.login-ecr.outputs.registry }}/${{ vars.AWS_PUBLIC_ECR_ALIAS }}/javascript-sample"
      run: |
        docker tag javascript-sample:latest  $PUBLIC_ECR:latest
        docker push  $PUBLIC_ECR:latest
